# This is a basic workflow to help you get started with Actions

name: Matlab

on:
  workflow_dispatch:


jobs:
  build:
    name: xxx 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Set up Matlab
        uses: matlab-actions/setup-matlab@master
      - name: Run command
        uses: matlab-actions/run-command@v1
        with:
          command: mytest

          
